export const PriceOptions: string[] = [
  "gratuit",
  "payant",
  "gratuit sous condition",
];

export const BooleanOptions: string[] = ["1", "0"];

export const TagOptions: string[] = [
  "Art contemporain",
  "Atelier",
  "BD",
  "Balade urbaine",
  "Brocante",
  "Cirque",
  "Concert",
  "Conférence",
  "Danse",
  "Ecrans",
  "Enfants",
  "Expo",
  "Festival",
  "Gourmand",
  "Histoire",
  "Humour",
  "Innovation",
  "Jeux 2024",
  "LGBT",
  "Littérature",
  "Loisirs",
  "Nature",
  "Nuit",
  "Paris fête les jeux",
  "Peinture",
  "Photo",
  "Salon",
  "Santé",
  "Sciences",
  "Solidarité",
  "Spectacle musical",
  "Sport",
  "Street-art",
  "Théâtre",
];
